### ISSUE TITLE
Device shows no formats available / not listed in Logic Pro

### ISSUE THREAD

**Issue by mattahorton** [gavv/libASPL#1] opened 2021-12-19 07:36 UTC
Hey @gavv 

Thanks so much for the work here. This has been so helpful for my project.

Right now, though, I'm really focused on getting the example working.

I can build it. I can install it. It shows up in system settings. It shows up in OBS.

However it does not show up in Logic Pro, and in Audio MIDI Setup, it lists "No valid formats available". 

What am I doing wrong here?

<img width="257" alt="Screen Shot 2021-12-18 at 11 49 44 PM" src="https://user-images.githubusercontent.com/5567285/146667435-4a5c7064-d234-4288-a2f2-876cf8e47bec.png">

**Comment by gavv** [comment] 2021-12-30 19:29
@mattahorton Hi! Thanks for your interest!

Sorry, this is a crazy month, I have almost no time right now.

Some ideas:

* does example work with Music or Chrome? it was correctly sending samples to netcat when I tested those apps
* what OS are you using? I've tested example on catalina and big sur
* you can look into syslog; the lib is tracing all requests made to device; you can find what properties are requested by the apps you tested; maybe some properties are missing in the lib? you can also see what format do the lib return

**Comment by mattahorton** [comment] 2022-01-09 03:50
- It does function and correctly send audio to netcat.
- I'm on Monterey on an m1.
- It has been a bit but I'm looking now and off-hand, the 'asil', 'spat', 'otua', and kAudioObjectPropertyModelName properties are not found.

**Comment by mattahorton** [comment] 2022-01-09 19:28
Discovered that:

1. The four char code properties being requested are backwards?
2. Even backwards only some of them map to things in the latest CoreAudio SDK. A handful map to other SDKs but not all of them. Like 'cfsz' which doesn't exist (but 'vfsz' does and is for virtual frame size I believe?)
3. They're all requested by Control Center.

For context, I'm on an M1 machine on Monterey. I think some of what's going on is Monterey bugs, some is undocumented features, and the rest is things I might be able to get working in libASPL. Not sure where to start on that last part.

**Comment by gavv** [comment] 2022-02-02 17:02
> The four char code properties being requested are backwards?

Seems that when we're converting that code to string for logging, we ignore endian, and thus on big-endian (m1) it's backwards. Will look at it.

> They're all requested by Control Center.

Then most likely that's not the source of the problem..

> does example work with Music or Chrome? it was correctly sending samples to netcat when I tested those apps
>> It does function and correctly send audio to netcat.
>> However it does not show up in Logic Pro, and in Audio MIDI Setup, it lists "No valid formats available".

OK, so the problem seems to be specific for this two apps, right? I never tested libASPL with them BTW.

With Logic Pro, which hides device for some reason, you man try to change some hard-coded properties: kAudioDevicePropertyTransportType (GetTransportType), kAudioDevicePropertyClockIsStable (GetClockIsStable), etc. Maybe, for example, the app hides virtual devices (kAudioDevicePropertyTransportType = kAudioDeviceTransportTypeVirtual).

With Audio MIDI Setup, you can try to change GetAvailablePhysicalFormats or GetAvailableVirtualFormats. Maybe the app looks for some format that the device doesn't declare to be supported.

You can also post driver logs. Maybe I could find something useful there.

**Comment by gavv** [comment] 2022-02-02 17:09
> Seems that when we're converting that code to string for logging, we ignore endian, and thus on big-endian (m1) it's backwards. Will look at it.

Pushed a fix.

**Comment by mattahorton** [comment] 2022-02-02 18:40
Thanks @gavv. I'll give this a look again.

**Comment by afigegoznaet** [comment] 2022-06-19 11:22
Hi there.
I'm curious if this got fixed, cause I am having the same exact issue on an M1

**Comment by afigegoznaet** [comment] 2022-06-19 14:20
Hello,
Apparently, the issue is related to GetAvailablePhysicalFormats() returning an empty list.
BTW, the issue is reproducible not only in logic pro, but also in garage band.
I was able to make device selectable / show available formats by returning a hardcoded array of formats in the calling function.
Should be easy to fix, I can submit a PR next week.

**Comment by afigegoznaet** [comment] 2022-06-23 09:32
Hi @gavv
Can you give me permission to submit a PR?

**Comment by gavv** [comment] 2022-06-24 11:17
@afigegoznaet Sure, you're welcome, thanks!

**Comment by afigegoznaet** [comment] 2022-06-24 19:11
I believe you need to add me to the project explicitly.

fatal: unable to access 'https://github.com/gavv/libASPL.git/': The requested URL returned error: 403

**Comment by gavv** [comment] 2022-06-24 23:17
@afigegoznaet Oh, you just need to fork the repo on github, push changes to your fork, and then create PR from the fork to this repo.

**Comment by gavv** [comment] 2022-11-25 15:19
We've merged the bugfix provided by @afigegoznaet.

With this fix, the device is now recognized by Audio MIDI Setup and Garage Band. Also I tested that Garage Band playback works well with libASPL device.

The change is available in main branch, I'll also tag a release soon.

**Comment by gavv** [comment] 2022-11-25 17:44
I've tagged new release v2.0.0 with the fix included: https://github.com/gavv/libASPL/releases/tag/v2.0.0

The major version was bumped because the fix breaks compatibility (changes signature for overridable functions). Since we're bumping major version anyway, I also did some cleanup in public interfaces (see release notes).

I'm closing this issue, but feel free to reopen if you encounter any problems with the fix.

**Closed as completed** 2022-11-25 17:45 UTC
Labels: bug
